ScrollDiv = ->
  if document.getElementById('m_log').scrollTop < document.getElementById('m_log').scrollHeight - (document.getElementById('m_log').offsetHeight)
    -1
    document.getElementById('m_log').scrollTop = document.getElementById('m_log').scrollTop + 30
  else
    document.getElementById('m_log').scrollTop = 0
  return

setInterval ScrollDiv, 50

# ---
# generated by js2coffee 2.2.0
#scroll = ->
#  i = i + speed
#  div = document.getElementById('m_log')
#  div.scrollTop = i
#  if i > div.scrollHeight - 160
#    i = 0
#  t1 = setTimeout('scroll()', 100)
#  return
#
#i = 0
#speed = 1
#scroll
